vimond_server/interval_operations/urls.py
from django.urls import path
from . import views

app_name = 'interval_operations'

urlpatterns = [
    path('api/process_intervals/', views.api_process_intervals, name='api_process_intervals'),
    path('', views.html_process_intervals, name='html_process_intervals'),
]

vimond_server/vimond_server/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('interval_operations.urls')),  
]

vimond_server/interval_operations/models.py
from django.db import models

# Create your models here.

vimond_server/interval_operations/views.py
from django.shortcuts import render
from django.http import JsonResponse
from rest_framework.decorators import api_view
from rest_framework.response import Response

from .interval_processors import calculate_intervals
from .view_utils import convert_to_intervals

@api_view(['POST'])
def api_process_intervals(request):
    if request.method == 'POST':
        data = request.data
        includes = data.get('includes', [])
        excludes = data.get('excludes', [])
        
        # print("INCLUDES\n", includes)
        # print("EXCLUDES\n", excludes)
  
        result = calculate_intervals(includes, excludes)
        return Response({'result': result})
    else:
        return Response({'error': 'Invalid request method'})


def html_process_intervals(request):
    result = None
    error_message = None

    if request.method == 'POST':
        includes = request.POST.get('includes', '')
        excludes = request.POST.get('excludes', '')

        try:
            includes_list = convert_to_intervals(includes) if includes else []
            excludes_list = convert_to_intervals(excludes) if excludes else []

            result = calculate_intervals(includes_list, excludes_list)

        except ValueError as e:
            error_message = str(e)

    return render(request, 'interval_operations/interval_operations.html', {'result': result, 'error_message': error_message})

vimond_server/interval_operations/templates/interval_operations/interval_operations.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Interval Result</title>
</head>
<body>
    <h1>Interval Result</h1>
    
    <form method="post" action="{% url 'interval_operations:html_process_intervals' %}">
        {% csrf_token %}
        <label for="includes">Includes:</label>
        <input type="text" name="includes" id="includes" >
        <br>
        <label for="excludes">Excludes:</label>
        <input type="text" name="excludes" id="excludes" >
        <br>
        <input type="submit" value="Calculate">
    </form>
    
    <h2>Result:</h2>
    {% if result %}
        <ul>
            {% for interval in result %}
                <li>{{ interval.0 }} - {{ interval.1 }}</li>
            {% endfor %}
        </ul>
    {% endif %}

    {% if error_message %}
    <div style="color: red;">
        <strong>Error:</strong> {{ error_message }}
    </div>
{% endif %}
</body>
</html>